baseURL = "https://toushi.maku.blog/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
title = "まくまく投資ノート"
# googleAnalytics = "UA-63069513-2"
googleAnalytics = "G-Q28XZ15ZKZ"

[markup.goldmark.renderer]
  unsafe = true

[params]
  sidebarLogo = "img/site-logo.png"
  image = "img/site-logo.png"
  facebookAppId = "525778660924912"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "a3565b62678da48be"
  # 下記は memoja.net 時代の ID
  # CustomSearchId = "partner-pub-6317852277883092:4842999464"

[module]
[[module.imports]]
  path = "github.com/maku77/hugo-module-maku-common"
[[module.imports]]
  path = "github.com/maku77/hugo-module-maku-blog"

