on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
        with:
          go-version: '^1.20'

      - name: Setup Hugo environment
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.111.3'
          extended: true  # Enable scss
        
      - name: Build
        run: hugo --minify -F

      - name: Generate ssh key
        run: echo "$SSH_PRIVATE_KEY" > ${{ runner.temp }}/key && chmod 600 ${{ runner.temp }}/key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with rsync
        run: >
          rsync -e 'ssh -i ${{ runner.temp }}/key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          -av public/ ${SSH_USER}@${SSH_HOST}:${DST_PATH}
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DST_PATH: ${{ secrets.DST_PATH }}
